

const actionTypes = {
    FETCH_USER: 'FETCH_USER',
    POST_LOGIN: 'POST_LOGIN',
    POST_SIGNUP: 'POST_SIGNUP',
    POST_SIGNOUT: 'POST_SIGNOUT',
    FETCH_RECIPES: 'FETCH_RECIPES',
    FETCH_RECIPE_DETAILS: 'FETCH_RECIPE_DETAILS',
    POST_RECIPE: 'POST_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    PUT_RECIPE: 'PUT_RECIPE'
};

export default actionTypes;
