

const actionTypes = {
    GET_USER: 'GET_USER',
    FETCH_RECIPES: 'FETCH_RECIPES',
    FETCH_RECIPE_DETAILS: 'FETCH_RECIPE_DETAILS',
    POST_RECIPE: 'POST_RECIPE',
    DELETE_RECIPE: 'DELETE_RECIPE',
    PUT_RECIPE: 'PUT_RECIPE'
};

export default actionTypes;
